fix(windows): redirect stdout/stderr
when pyinstaller is used on windows with the --windowed option, accessing stdout/err leads to

AttributeError: 'NoneType' object has no attribute 'flush'.

The access happends internally in trame_server but it could be more.
We apply the suggestion of [1] from the pyinstaller documentation.
[1] https://pyinstaller.org/en/latest/common-issues-and-pitfalls.html#sys-stdin-sys-stdout-and-sys-stderr-in-noconsole-windowed-applications-windows-only